<?php
    $language = 'en';
    $allowChange = \UPS\Shipping\Helper\Config::LISTEULANGUAGES;
    $localCode = trim($block->getAdminLanguageCode());
    $countryBase = $block->getCountryCode();
    $selectedCountry = $country1 = strtolower($countryBase);
    $arrayTitles = \UPS\Shipping\Helper\Config::LIST_TITLE_ACCOUNT;
if (!empty($localCode)) {
    $arrayLanguages = explode("_", $localCode);
    $languageTitle = trim($arrayLanguages[0]);
    if (in_array($languageTitle, ['pl','de','nl'])) {
        $arrayTitles = \UPS\Shipping\Helper\Config::LIST_TITLE_ACCOUNT_POLISH;
    }
    if (in_array($languageTitle, ['it','es'])) {
        $arrayTitles = \UPS\Shipping\Helper\Config::LIST_TITLE_ACCOUNT_SPANISH;
    }
    $languageCheck = trim($arrayLanguages[0]) . '_' . trim($countryBase);
    if (in_array($languageCheck, $allowChange)) {
        $language = $arrayLanguages[0];
    }
}
    $dataError = $block->dataFormSession();
    if (!isset($dataError['InvoiceDate'])) {
        $dataError['InvoiceDate'] = "";
    }
    $noteAccountNumber1 = __("I do not have a UPS Account Number and would ");
    $noteAccountNumber2 = __("like");
    $noteAccountNumber3 = __(" to get one from the plug-in");
    $noteAccountNumber = $noteAccountNumber1 . $noteAccountNumber2 . $noteAccountNumber3;

    $noteAccountNumberUS1 = __("I don’t have a UPS account number and would ");
    $noteAccountNumberUS3 = __(" to get one with discounted rates from the plug-in");
if ('us' == $country1) {
    $usLink = __("<a target='_blank' href='https://www.ups.com/assets/resources/media/en_US/CP5_US.pdf'><i>See UPS Terms of Service</i></a>");
    $noteAccountNumber = $noteAccountNumberUS1 . $noteAccountNumber2 . $noteAccountNumberUS3 . ' ' . $usLink;
}
    $listStates = $block->getListStates();
?>
<div class="entry-edit form-inline">
    <div class="card-header" id="headingTwo" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
        <div class="page-main-actions">
            <h2 class="titleAccount" style="margin-bottom:0%"><?php echo __('ACCOUNT') ?></h2>
        </div>
    </div>
    <form action="<?php echo $block->getUrl('upsshipping/config/saveAccount') ?>" method="post" id="form-account">
        <div>
            <fieldset class="fieldset admin__fieldset">
            <legend>
                <b><span><?php if ('us' == $selectedCountry) {
                        echo __("For more information on UPS Plugins please click <a target='_blank' href='https://www.ups.com/plugins'>this link</a> (opens in a new browser window)");
                         } else {
                             echo __("For more information on UPS Plugins please click <a target='_blank' href='https://www.ups.com/gb/en/business-solutions/expand-your-online-business/ecommerce-plug-ins.page'>this link</a> (opens in a new browser window)", [$country1, $language]);
                         } ?></span></b>
            </legend>
            <br/>
            </fieldset>
        </div>
        <div style="background: #e9e9e9;">
            <h3 style="text-align: center; padding: 10px;"><?php echo __('Step 1: Account Linking');?></h3>
        </div>
        <div style="padding: 0px 20px 0px 20px;">
            <div>
                <fieldset class="fieldset admin__fieldset">
                <legend>
                    <b><span><?php echo __('Please choose one of the account linking options below and fill the necessary form fields to get started.') ?></span></b>
                </legend>
                <br/>
                </fieldset>
            </div>
            <div>
                <fieldset class="fieldset admin__fieldset acc_link_opt">
                    <legend>
                        <input type="radio" <?php if ($dataError['optradio'] == 4) { echo 'Checked';} ?> name="optradio" id="accountWithUsrPwd" value="4"><b> <?php echo __('I have a UPS Account Number WITH Username and password') ?></b>
                    </legend>
                    <br/>
                    <div class="admin__fieldset acc_link_fields <?php if ($dataError['optradio'] == 4) { echo 'accountWithUsrPwd_show';} ?>" style="width: 50%;">
                        <div class="admin__field field required accountWithUsrPwd_show">
                            <label class="remove_pointer label admin__field-label ">
                            <span><?php echo __('Username:') ?></span>
                            </label>
                            <div class="admin__field-control">
                                <input maxlength="35" value="" name="AccountWithUser" id="AccountWithUser" data-validate-hidden="{'required': true, 'validate-rule': ''}" type="text" class="admin__control-text" style="width: 80%;">
                            </div>
                            <div class="admin__field-tooltip" style="margin-left: -8% !important;">
                                <a class="admin__field-tooltip-action"></a>
                                <div class="admin__field-tooltip-content stype-right"><?php echo __("UPS site login Username") ?></div>
                            </div>
                        </div>
                        <div class="admin__field field required accountWithUsrPwd_show">
                            <label class="remove_pointer label admin__field-label ">
                            <span><?php echo __('Password:') ?></span>
                            </label>
                            <div class="admin__field-control">
                                <input maxlength="35" value="" name="AccountWithPwd" id="AccountWithPwd" data-validate-hidden="{'required': true, 'validate-rule': ''}" type="password" class="admin__control-text" style="width: 80%;">
                            </div>
                            <div class="admin__field-tooltip" style="margin-left: -8% !important;">
                                <a class="admin__field-tooltip-action"></a>
                                <div class="admin__field-tooltip-content stype-right"><?php echo __("UPS site login Password") ?></div>
                            </div>
                        </div>
                        <div class="admin__field field required accountWithUsrPwd_show">
                            <label class="remove_pointer label admin__field-label ">
                            <span><?php echo __('Account Number:') ?></span>
                            </label>
                            <div class="admin__field-control">
                                <input value="" maxlength="6" name="AccountNumber2" id="AccountNumber2" data-validate-hidden="{'required': true, 'validate-rule': 'accountNumber'}" type="text" class="admin__control-text" style="width: 80%;">
                            </div>
                            <div class="admin__field-tooltip" style="margin-left: -8% !important;">
                                <a class="admin__field-tooltip-action"></a>
                                <div class="admin__field-tooltip-content stype-right"><?php echo __('A unique six character alphanumeric number that identifies your account') ?></div>
                            </div>
                        </div>
                        <div class="admin__field field required accountWithUsrPwd_show">
                            <label class="remove_pointer label admin__field-label ">
                            <span><?php echo __('Account Name:') ?></span>
                            </label>
                            <div class="admin__field-control">
                                <input maxlength="35" value="" name="AccountName2" id="AccountName2" data-validate-hidden="{'required': true, 'validate-rule': ''}" type="text" class="admin__control-text" style="width: 80%;">
                            </div>
                        </div>
                        <div class="admin__field field accountWithUsrPwd_show">
                            <label class="remove_pointer label admin__field-label ">
                            <span><?php echo __('Access Key:') ?></span>
                            </label>
                            <div class="admin__field-control">
                                <input value="" maxlength="35" name="AccountAccess" id="AccountAccess" data-validate-hidden="{'required': true, 'validate-rule': ''}" type="text" class="admin__control-text" style="width: 80%;">
                                <br><small style="width: 80%; color: green;">Leave this field empty to generate new access key</small>
                            </div>
                            <div class="admin__field-tooltip" style="margin-left: -8% !important;">
                                <a class="admin__field-tooltip-action"></a>
                                <div class="admin__field-tooltip-content stype-right"><?php echo __('Acess licence number associated with your account.') ?></div>
                            </div>
                        </div>
                    </div>
                    <div class="useful-info accountWithUsrPwd_show">
                        <p><b>Useful Info:-</b><br>
                            <span><?php echo __("Please note: Visit the UPS Developer Kit page by following this link for getting your Access Key. You can find a detailed step-by-step guide on how to get your access key in this link.");?></span>
                            <span style="color:#1e91cf;">
                                <br>
                                <
                                <a target="_blank" style="color:#1e91cf;" href="<?php echo __('https://www.ups.com/dpui/upsdeveloperkit'); ?>">
                                    <?php echo __("https://www.ups.com/dpui/upsdeveloperkit"); ?>
                                </a>
                                >
                            </span>
                        </p>
                    </div>
                </fieldset>
            </div>
            <div>
                <fieldset class="fieldset admin__fieldset acc_link_opt">
                    <legend>
                        <input type="radio" <?php if ($dataError['optradio'] == 0) { echo 'Checked';} ?> name="optradio" id="notAccount" value="0"><b>
                            <?php echo $noteAccountNumber; ?></b>
                    </legend>
                    <br/>
                    <div class="admin__fieldset acc_link_fields <?php if ($dataError['optradio'] == 0) { echo 'accountWithOutNumber_show';} ?>" style="width: 50%;">
                        <?php if ('us' == $country1) { ?>
                            <div>
                                <label class="remove_pointer label admin__field-label accountWithOutNumber_show">
                                <span><?php echo __('Business to business shipments from the US to Europe require VAT number. If you do not have a VAT number at this time, you can add to your account at a later date on UPS.com.') ?></span>
                                </label>
                            </div>
                        <?php } ?>
                        <div class="admin__field field accountWithOutNumber_show <?php if ('us' == $country1) { echo 'us_label_note';} ?>">
                            <label class="remove_pointer label admin__field-label">
                            <span><?php echo __('VAT Number:') ?></span>
                            </label>
                            <div class="admin__field-control">
                            <input maxlength="15" value="<?= $dataError['VATNumber'] ?>" name="VATNumber" id="VATNumber" type="text" class="admin_control-input" style="width: 80%;">
                            </div>
                        </div>
                        <?php if ('us' != $country1) {?>
                        <div class="admin__field field accountWithOutNumber_show">
                            <label class="remove_pointer label admin__field-label">
                            <span><?php echo __('Promo Code:') ?></span>
                            </label>
                            <div class="admin__field-control">
                            <input maxlength="9" value="<?= $dataError['PromoCode'] ?>" name="PromoCode" id="PromoCode" type="text" class="admin_control-input" style="width: 80%;">
                            </div>
                        </div>
                        <?php } ?>
                    </div>
                    <div class="useful-info accountWithOutNumber_show">
                        <b>Useful Info:-</b>
                        <div>
                            <label class="remove_pointer label admin__field-label accountWithOutNumber_show">
                            <span><?php echo __('Please Note: Shippers are prohibited from shipping dangerous goods or hazardous materials using the account opened in this application.') ?></span>
                            </label>
                        </div>
                        <div class="marginBottom accountWithOutNumber_show">
                            <label class="remove_pointer label admin__field-label">
                            <span><?php echo __('Your account will support deliveries to authorized UPS Access Point™ locations after 24 hours.') ?></span>
                            </label>
                        </div>
                        <div>
                            <label class="remove_pointer label admin__field-label accountWithOutNumber_show">
                            <span><?php echo __("You can find more information on dangerous goods and how UPS can support you shipping them on this link <br /><a target='_blank' href=https://www.ups.com/%1/%2/help-center/packaging-and-supplies/special-care-shipments/global-dangerous-goods.page>[https://www.ups.com/%1/%2/help-center/packaging-and-supplies/special-care-shipments/global-dangerous-goods.page]</a>", [$country1, $language]) ?></span>
                            </label>
                        </div>
                    </div>
                </fieldset>
            </div>
        </div>
        <p><br></p>
        <div style="background: #e9e9e9;">
            <h3 style="text-align: center; padding: 10px;"><?php echo __('Step 2: Merchant Details and Pickup Address');?></h3>
        </div>
        <div style="padding: 0px 20px 0px 20px;">
            <div class="row">
            <div class="col-m-12 col-l-6 col-xl-6">
                <fieldset class="admin__fieldset">
                <div class="admin__field field required">
                    <label class="remove_pointer label admin__field-label"><span><?php echo __('Title:') ?></span></label>
                    <div class="admin__field-control control">
                        <select id="Title" name="Title"class="select select admin__control-select">
                            <?php foreach ($arrayTitles as $key => $value) { ?>
                                <option <?php if ($dataError['Title'] == $value) {echo 'selected';} ?>
                                value="<?= $value ?>"><?= __($value) ?></option>
                            <?php } ?>
                        </select>
                    </div>
                </div>
                <div class="admin__field field required">
                    <label class="remove_pointer label admin__field-label"><span><?php echo __('Full name:') ?></span></label>
                    <div class="admin__field-control control width-input">
                        <input maxlength="35" value="<?= $dataError['CustomerName'] ?>" id="CustomerName"
                        name="CustomerName" data-validate="{'required': true, 'validate-rule': ''}"
                        type="text" class="admin__control-text">
                    </div>
                </div>
                <div class="admin__field field  required">
                    <label class="remove_pointer label admin__field-label"><span><?php echo __('Company:') ?></span></label>
                    <div class="admin__field-control control width-input">
                        <input maxlength="35" value="<?= $dataError['CompanyName'] ?>" id="CompanyName"
                        name="CompanyName" data-validate="{'required': true, 'validate-rule': ''}"
                        type="text" class="admin__control-text">
                    </div>
                </div>
                <div class="admin__field required">
                    <label class="remove_pointer admin__field-label"><span><?php echo __('Email:') ?></span></label>
                    <div class="admin__field-control control width-input">
                        <input maxlength="50" value="<?= $dataError['AddressEmail'] ?>" name="AddressEmail"
                        id="AddressEmail" data-validate="{'required': true, 'validate-rule': 'email'}" type="text"
                        class="admin__control-text">
                    </div>
                </div>
                <div class="admin__field field  required">
                    <label class="remove_pointer label admin__field-label"><span><?php echo __("Phone &nbsp;number:") ?></span></label>
                    <div class="admin__field-control control width-input">
                        <input maxlength="15" value="<?= $dataError['PhoneNumber'] ?>" name="PhoneNumber"
                        id="PhoneNumber" data-validate="{'required': true, 'validate-rule': ''}" type="text"
                        class="admin__control-text">
                    </div>
                </div>
                </fieldset>
            </div>
            <div class="col-m-12 col-l-6 col-xl-6">
                <fieldset class="fieldset admin__fieldset ">
                    <div class="admin__field field">
                        <label  class="remove_pointer label admin__field-label"><span><?php echo __('Address type:') ?></span></label>
                        <div class="admin__field-control data-grid-search-control-wrap width-input">
                            <input maxlength="50" value="<?= $dataError['AddressType'] ?>" name="AddressType"
                            id="AddressType" placeholder="<?php echo __('Example: Warehouse, Branch #1') ?>" type="text" class="admin__control-text">
                        </div>
                        <div class="admin__field-tooltip">
                                <a class="admin__field-tooltip-action"></a>
                                <div class="admin__field-tooltip-content stype-right">
                                    <?php echo __("Reference name that will be associate with an account. For example warehouse 1, warehouse 2,  Store 1, Store 2 etc. You can freely chose the name as per your requirement") ?></div>
                            </div>
                    </div>
                    <div class="admin__field field required">
                        <label class="remove_pointer label admin__field-label"><span><?php echo __('Pickup Address:') ?></span></label>
                        <div class="admin__field-control control data-grid-search-control-wrap width-input">
                            <input maxlength="35" value="<?= $dataError['AddressLine1'] ?>" name="AddressLine1"
                            id="AddressLine1" data-validate="{'required': true}"
                            placeholder="<?php echo __('Street Address') ?>" type="text" class="admin__control-text">
                        </div>
                        <div class="admin__field-tooltip">
                            <a class="admin__field-tooltip-action"></a>
                            <div class="admin__field-tooltip-content stype-right">
                                <?php echo __("Use registered pickup address. <br />If you have any difficulties understanding which address to use, please contact your local UPS sales representative or call the support phone number provided on the “About” page") ?></div>
                        </div>
                    </div>
                    <div class="admin__field field">
                        <label class="remove_pointer label admin__field-label"><span></span></label>
                        <div class="admin__field-control control data-grid-search-control-wrap width-input">
                            <input maxlength="35" value="<?= $dataError['AddressLine2'] ?>" name="AddressLine2"
                            id="AddressLine2"
                            placeholder="<?php echo __('Apartment, Suite, Unit, Building, Floor, etc.') ?>" type="text" class="admin__control-text">
                        </div>
                    </div>
                    <div class="admin__field field">
                        <label class="remove_pointer label admin__field-label"><span></span></label>
                        <div class="admin__field-control control data-grid-search-control-wrap width-input">
                            <input maxlength="35" value="<?= $dataError['AddressLine3'] ?>" name="AddressLine3"
                            id="AddressLine3" placeholder="<?php echo __('Department, c/o, etc.') ?>"
                            type="text" class="admin__control-text">
                        </div>
                    </div>
                    <?php if ('us' == $country1) {?>
                        <div class="admin__field field required">
                            <label class="remove_pointer label admin__field-label"><span><?php echo __('State/Province:') ?></span></label>
                            <div class="admin__field-control control">
                                <select id="StateProvinceCode" name="StateProvinceCode" data-validate="{'required': true, 'validate-rule': ''}" class="select select admin__control-select" >
                                    <?php foreach ($listStates as $value) { ?>
                                        <option <?php if ($dataError['StateProvinceCode'] == $value['code']) {echo 'selected';} ?> value="<?= $value['code'] ?>"><?= __($value['name']) ?></option>
                                    <?php } ?>
                                </select>
                            </div>
                        </div>
                    <?php } ?>
                    <div class="admin__field field  required">
                        <label class="remove_pointer label admin__field-label"><span><?php echo __('Pickup Postal Code:') ?></span></label>
                        <div class="admin__field-control control width-input">
                            <input value="<?php echo $dataError['PostalCode'] ?>" maxlength="9" name="PostalCode"
                            id="PostalCode" data-validate="{'required': true, 'validate-rule': ''}"
                            type="text" class="admin__control-text <?php echo (isset($dataError['submit_account']) && $dataError['submit_account'] == 'PickupAddressCandidate') ? 'admin__field-error' : '' ?>">
                        </div>
                        <div class="admin__field-tooltip">
                            <a class="admin__field-tooltip-action"></a>
                            <div class="admin__field-tooltip-content stype-right">
                                <?php echo __("The format of the postal code should exactly match the one provided in the registered pickup address. If you have any difficulties understanding which address to use, please contact your local UPS sales representative or call the support phone number provided on the “About” page") ?></div>
                        </div>
                    </div>
                    <div class="admin__field field  required">
                        <label class="remove_pointer label admin__field-label"><span><?php echo __('City:') ?></span></label>
                        <div class="admin__field-control control width-input">
                            <input maxlength="30" value="<?= $dataError['AccountCity'] ?>" name="AccountCity"
                            id="AccountCity" data-validate="{'required': true, 'validate-rule': ''}"
                            type="text" class="admin__control-text <?php echo (isset($dataError['submit_account']) && $dataError['submit_account'] == 'PickupAddressCandidate') ? 'admin__field-error' : '' ?>">
                        </div>
                    </div>
                    <div class="admin__field field">
                        <label class="remove_pointer label admin__field-label"><span><?php echo __('Country/Territory:'); ?></span>
                    </label>
                        <div class="admin__field-control control width-input">
                            <?php $countryCode = $block->getCountryCode() ?>
                            <?php foreach ($block->getListContry() as $country) {
                                if ($country['id'] == $countryCode) {?>
                                <input type="hidden" name="CountryCode" value="<?=$countryCode?>">
                                <input disabled type="text" class="admin__control-text" name="CountryCode"
                                id="CountryCode" value="<?php echo $country['value']; ?>">
                                <?php } ?>
                            <?php } ?>
                        </div>
                    </div>
                </fieldset>
            </div>
            </div>
        </div>
        <div class="row">
            <div class="admin__field page-main-actions">
                <div class="page-actions">
                    <button type="submit" name="submit_account" class="button-next action-default primary ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only"  role="button" aria-disabled="false">
                        <span class="ui-button-text">
                            <span><?= __('Get started') ?></span>
                        </span>
                    </button>
                </div>
            </div>
        </div>
        <input type="hidden" id="ioBlackBox" name="ioBlackBox" />
        <input type="hidden" name="accountvalidatemessage" id="accountvalidatemessage" value="<?php echo __('Some of the data you entered is not valid. Please check again.')?>">
        <input type="hidden" name="commonvalidatemessage" id="commonvalidatemessage" value="<?php echo __('Some of the data you entered is not valid. Please check again.')?>">
        <input type="hidden" name="invoicedatevalue" id="invoicedatevalue" value="<?= $dataError['InvoiceDate'] ?>">
        <input type="hidden" name="optradiovalue" id="optradiovalue" value="<?= $dataError['optradio'] ?>">
        <input name="form_key" type="hidden" value="<?php echo $block->getFormKey();?>">
    </form>
</div>
<?php if ('us' == $selectedCountry) {
    ?>
    <div style="padding-top: 1em; line-height: 1.5;">
        <div class="row">
            <div class="col-l-12" style="color: #777;">
                <?php echo '© ' . date("Y") .' United Parcel Service of America, Inc. <br />UPS,  the UPS Shield trademark, the UPS Ready mark, the UPS Developer Kit mark and the Color Brown are trademarks of United Parcel Service of America, Inc. All Rights Reserved.';
                ; ?>
            </div>
        </div>
    </div>
<?php } ?>
<script type="text/x-magento-init">
    {
        "*": {
            "UPS_Shipping/js/account": {}
        }
    }
</script>
